### ISSUE TITLE
Non continuous video file produced.

### ISSUE THREAD

**Issue by benjgorman** [timscaffidi/ofxVideoRecorder#15]
Hi I'm attempting to use this to record some openframework output. 

I have it producing a video file, but it looks like one of those scrolling sidewalk adverts, the frames scroll upwards instead of proceeding like a normal video. Any idea why?

[warning] ofThread: - name: Thread 4 - Calling startThread with verbose is deprecated.
[warning] ofThread: - name: Thread 2 - Calling startThread with verbose is deprecated.
ffmpeg version 2.6.1 Copyright (c) 2000-2015 the FFmpeg developers
  built with llvm-gcc 4.2.1 (LLVM build 2336.11.00)
  configuration: --prefix=/Volumes/Ramdisk/sw --enable-gpl --enable-pthreads --enable-version3 --enable-libspeex --enable-libvpx --disable-decoder=libvpx --enable-libmp3lame --enable-libtheora --enable-libvorbis --enable-libx264 --enable-avfilter --enable-libopencore_amrwb --enable-libopencore_amrnb --enable-filters --enable-libgsm --enable-libvidstab --enable-libx265 --disable-doc --arch=x86_64 --enable-runtime-cpudetect
  libavutil      54. 20.100 / 54. 20.100
  libavcodec     56. 26.100 / 56. 26.100
  libavformat    56. 25.101 / 56. 25.101
  libavdevice    56.  4.100 / 56.  4.100
  libavfilter     5. 11.102 /  5. 11.102
  libswscale      3.  1.101 /  3.  1.101
  libswresample   1.  1.100 /  1.  1.100
  libpostproc    53.  3.100 / 53.  3.100
Input #0, rawvideo, from '/Users/benjgorman/Code/OF_ROOT/addons/ofxTimeline/duplicate_lips/bin/data/ofxvrpipe0':
  Duration: N/A, start: 0.000000, bitrate: 566231 kb/s
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1024x768, 566231 kb/s, 30 tbr, 30 tbn, 30 tbc
Please use -b:a or -b:v, -b is ambiguous
Output #0, mov, to '/Users/benjgorman/Code/OF_ROOT/addons/ofxTimeline/duplicate_lips/bin/data/testMovie2015-04-16-03-06-40-055.mov':
  Metadata:
    encoder         : Lavf56.25.101
    Stream #0:0: Video: mpeg4 (mp4v / 0x7634706D), yuv420p, 1024x768, q=2-31, 800 kb/s, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc56.26.100 mpeg4
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> mpeg4 (native))
Press [q] to stop, [?] for help
frame=   11 fps=0.0 q=2.5 size=      95kB time=00:00:00.36 bitrate=2112.2kbits/s    
frame=   27 fps= 24 q=6.3 size=     208kB time=00:00:00.90 bitrate=1897.6kbits/s    
frame=   42 fps= 25 q=10.4 size=     286kB time=00:00:01.40 bitrate=1671.6kbits/s    
frame=   58 fps= 26 q=14.1 size=     356kB time=00:00:01.93 bitrate=1508.2kbits/s    
frame=   71 fps= 26 q=13.0 size=     399kB time=00:00:02.36 bitrate=1379.8kbits/s    
frame=   86 fps= 27 q=12.4 size=     465kB time=00:00:02.86 bitrate=1329.8kbits/s    
frame=   98 fps= 26 q=16.5 size=     515kB time=00:00:03.26 bitrate=1291.1kbits/s    
frame=  111 fps= 26 q=23.5 size=     560kB time=00:00:03.70 bitrate=1240.6kbits/s    
frame=  121 fps= 25 q=20.6 size=     583kB time=00:00:04.03 bitrate=1184.7kbits/s    
frame=  136 fps= 26 q=22.8 size=     642kB time=00:00:04.53 bitrate=1160.2kbits/s    
frame=  152 fps= 26 q=22.3 size=     690kB time=00:00:05.06 bitrate=1115.6kbits/s    
frame=  166 fps= 26 q=22.8 size=     731kB time=00:00:05.53 bitrate=1082.9kbits/s    
frame=  181 fps= 26 q=22.2 size=     773kB time=00:00:06.03 bitrate=1050.0kbits/s    
frame=  196 fps= 26 q=25.8 size=     831kB time=00:00:06.53 bitrate=1041.5kbits/s    
frame=  212 fps= 27 q=25.5 size=     876kB time=00:00:07.06 bitrate=1015.4kbits/s    
frame=  227 fps= 27 q=25.2 size=     918kB time=00:00:07.56 bitrate= 993.6kbits/s    
frame=  242 fps= 27 q=20.0 size=     971kB time=00:00:08.06 bitrate= 985.7kbits/s    
frame=  258 fps= 27 q=22.8 size=    1018kB time=00:00:08.60 bitrate= 970.0kbits/s    
frame=  273 fps= 27 q=26.7 size=    1062kB time=00:00:09.10 bitrate= 956.2kbits/s    
frame=  289 fps= 27 q=22.9 size=    1111kB time=00:00:09.63 bitrate= 944.9kbits/s    
frame=  304 fps= 27 q=24.2 size=    1164kB time=00:00:10.13 bitrate= 941.2kbits/s    
frame=  320 fps= 28 q=23.9 size=    1211kB time=00:00:10.66 bitrate= 930.3kbits/s    
frame=  335 fps= 28 q=26.3 size=    1260kB time=00:00:11.16 bitrate= 924.1kbits/s    
frame=  350 fps= 28 q=19.5 size=    1315kB time=00:00:11.66 bitrate= 923.3kbits/s    
frame=  364 fps= 28 q=26.4 size=    1359kB time=00:00:12.13 bitrate= 917.2kbits/s    
frame=  380 fps= 28 q=23.8 size=    1405kB time=00:00:12.66 bitrate= 908.9kbits/s    
frame=  396 fps= 28 q=23.0 size=    1449kB time=00:00:13.20 bitrate= 899.2kbits/s    
frame=  411 fps= 28 q=25.1 size=    1508kB time=00:00:13.70 bitrate= 901.6kbits/s    
frame=  426 fps= 28 q=21.6 size=    1551kB time=00:00:14.20 bitrate= 894.9kbits/s    
frame=  441 fps= 28 q=24.6 size=    1597kB time=00:00:14.70 bitrate= 890.0kbits/s    
frame=  457 fps= 28 q=25.3 size=    1649kB time=00:00:15.23 bitrate= 887.0kbits/s    
frame=  472 fps= 28 q=27.0 size=    1709kB time=00:00:15.73 bitrate= 889.8kbits/s    
frame=  488 fps= 28 q=31.0 size=    1786kB time=00:00:16.26 bitrate= 899.4kbits/s    
frame=  503 fps= 28 q=31.0 size=    1859kB time=00:00:16.76 bitrate= 908.3kbits/s    
frame=  519 fps= 28 q=31.0 size=    1946kB time=00:00:17.30 bitrate= 921.3kbits/s    
frame=  534 fps= 28 q=31.0 size=    2024kB time=00:00:17.80 bitrate= 931.7kbits/s    
frame=  549 fps= 28 q=31.0 size=    2096kB time=00:00:18.30 bitrate= 938.2kbits/s    
frame=  565 fps= 28 q=31.0 size=    2173kB time=00:00:18.83 bitrate= 945.4kbits/s    
frame=  577 fps= 28 q=31.0 size=    2236kB time=00:00:19.23 bitrate= 952.4kbits/s    
frame=  590 fps= 28 q=24.8 size=    2309kB time=00:00:19.66 bitrate= 961.8kbits/s    
frame=  605 fps= 28 q=31.0 size=    2384kB time=00:00:20.16 bitrate= 968.4kbits/s    
frame=  619 fps= 28 q=31.0 size=    2455kB time=00:00:20.63 bitrate= 974.6kbits/s    
frame=  634 fps= 28 q=31.0 size=    2531kB time=00:00:21.13 bitrate= 981.0kbits/s    
frame=  643 fps= 28 q=31.0 size=    2579kB time=00:00:21.43 bitrate= 985.6kbits/s    
frame=  659 fps= 28 q=31.0 size=    2659kB time=00:00:21.96 bitrate= 991.6kbits/s    
frame=  674 fps= 28 q=24.8 size=    2742kB time=00:00:22.46 bitrate= 999.8kbits/s    
frame=  690 fps= 28 q=31.0 size=    2826kB time=00:00:23.00 bitrate=1006.6kbits/s    
frame=  704 fps= 28 q=31.0 size=    2901kB time=00:00:23.46 bitrate=1012.7kbits/s    
frame=  719 fps= 28 q=31.0 size=    2976kB time=00:00:23.96 bitrate=1017.3kbits/s    
frame=  734 fps= 28 q=24.8 size=    3059kB time=00:00:24.46 bitrate=1024.3kbits/s    
frame=  750 fps= 28 q=31.0 size=    3145kB time=00:00:25.00 bitrate=1030.6kbits/s    
frame=  765 fps= 28 q=31.0 size=    3223kB time=00:00:25.50 bitrate=1035.6kbits/s    
frame=  780 fps= 28 q=31.0 size=    3303kB time=00:00:26.00 bitrate=1040.7kbits/s    
frame=  796 fps= 28 q=31.0 size=    3394kB time=00:00:26.53 bitrate=1047.9kbits/s    
frame=  812 fps= 28 q=31.0 size=    3476kB time=00:00:27.06 bitrate=1052.2kbits/s    
frame=  826 fps= 28 q=31.0 size=    3549kB time=00:00:27.53 bitrate=1056.0kbits/s    
frame=  842 fps= 28 q=24.8 size=    3637kB time=00:00:28.06 bitrate=1061.4kbits/s    
frame=  854 fps= 28 q=24.8 size=    3699kB time=00:00:28.46 bitrate=1064.5kbits/s    
frame=  870 fps= 28 q=31.0 size=    3785kB time=00:00:29.00 bitrate=1069.1kbits/s    
[rawvideo @ 0x103024800] Invalid buffer size, packet size 2045952 < expected frame_size 2359296
Error while decoding stream #0:0: Invalid argument
frame=  879 fps= 27 q=31.0 size=    3833kB time=00:00:29.30 bitrate=1071.6kbits/s    
frame=  879 fps= 27 q=31.0 Lsize=    3837kB time=00:00:29.30 bitrate=1072.8kbits/s    
video:3833kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.119554%

**Comment by timscaffidi** [comment]
it is hard for me to say exactly without seeing your code, but It looks like you are sending either too much or too little information for each frame. For example you might be sending a 640x480 frame of pixels but the recorder is expecting 1024x768, or vise-versa.

**Comment by benjgorman** [comment]
I had this at the end of my setup method.

if(!vidRecorder.isInitialized())
{
                   vidRecorder.setup(fileName+ofGetTimestampString()+fileExt, ofGetWidth(), ofGetHeight(), 30); // no audio
           
}

Now I had the window mode set to fullscreen intitially and that gave me scanlines on the output, so I made it not full screen and I got the frames I already mentioned and then I set it to 640, 480 and I got more scanlines.




I was using this code in my update loop

    ofImage img;
    img.grabScreen(0, 0, ofGetWidth(), ofGetHeight());
    
  
    vidRecorder.addFrame(img.getPixelsRef());

**Comment by timscaffidi** [comment]
I would advise against using ofGetWidth/Height with the video recorder as these values can change if you resize the window, and also I don't know that they will have the correct values if called within the setup function, as the window may not have been given its final size yet. Try hardcoding the width and height in both the setup method and within your update method, this should solve your problem.

I usually draw my entire scene to a FBO which has a fixed size (1920x1080 for example), then I can easily get the pixels from the FBO and save to the recorder. This has the added benefit of allowing me to draw the FBO to the screen at any size: should I need to support different resolution displays, just draw the FBO to fit within the window.

**Comment by benjgorman** [comment]
Aw man that worked perfectly! Great addon.

How would you do the FBO object?

**Comment by timscaffidi** [comment]
OF comes with an FBO example in the examples/gl/fboTrailsExample folder. If you need additional help with FBOs, make a topic in the OF forums and I'll be glad to look at it there.

**Comment by samelie** [comment]
Hi Tim, the addon works great with the videoGrabber, I have been struggling to get it recording from an FBO. This is what I get: [gif](http://gph.is/1RpIEUS)

I'm modding the example _trails_ you mentioned. 
I allocate by ofPixels like so `fboPix.allocate(640,480,OF_PIXELS_RGBA)`
Then I do:
`rgbaFbo.readToPixels(fboPix);
vidRecorder.addFrame(fboPix);`

I've made sure the videoRecorder.setup width/height matches. Could the pixel data
Would you be so kind as to updating the example with a working FBO version? I'm all out of ideas.

**Comment by kritzikratzi** [comment]
@samelie you should probably create a new bug. this seems non related. 
anyways, try rgb, instead of rgba!

**Comment by timscaffidi** [comment]
@samelie , I believe @kritzikratzi is correct. Using RGBA for the FBO will not work because the video grabber is expecting RGB. The resulting gif you posted looks so strange because because you are sending 4 byte per pixel, and the video grabber is expecting 3.

**Comment by samelie** [comment]
`fbo.readToPixels(fboPixels);
    for (int i = 0; i < fboWidth * fboHeight; i++) {
        int pix = i * 4;
        int pixRgb = i * 3;
        int r = fboPixels[pix]; 
        int g = fboPixels[pix + 1];
        int b = fboPixels[pix + 2]; 
        recorderPixels[pixRgb] = r;
        recorderPixels[pixRgb + 1] = g;
        recorderPixels[pixRgb + 2] = b;
    }
    if (bRecording) {
        bool success = vidRecorder.addFrame(recorderPixels);`

Ahha, nice one, my shader outputs RGBA! Thanks guys, works great!
