### ISSUE TITLE
OF 0.9.0

### ISSUE THREAD

**Issue by smallfly** [timscaffidi/ofxVideoRecorder#27]
I have created a branch for OF 0.9.0: https://github.com/smallfly/ofxVideoRecorder/tree/0.9.0

Maybe you could create a 0.9.0 branch on your GitHub repo and I could create a PR for these small updates, or do you prefer to push these to the Master right away?

Cheers,

**Comment by timscaffidi** [comment]
Are these changes backwards compatible with OF 0.8.4? If so then I say just submit a PR to master

**Comment by smallfly** [comment]
They are not.

**Comment by smallfly** [comment]
Would you be open to some 'house keeping'? I mean to make the add-on easier to read, and to follow a bit more the way other OF add-ons' code is formatted.

For example, adding 'separators' in between methods:
```//---------------------------------------- ```

Creating specific .h and .cpp for the ofxVideoDataWriterThread and ofxAudioDataWriterThread.

**Comment by timscaffidi** [comment]
I've created a 0.9.0 branch. I think we can definitely do some cleanup and your suggestions make sense. Lets keep the cleanup out of master for now and then once OF0.9.0 is released I'll make a tag for 0.8.4 and merge 0.9.0 into master.

**Comment by smallfly** [comment]
Great.

**Comment by smallfly** [comment]
Hi,
I have just made the initial PR to make the add-on compatible with OF 0.9.0.

I will now start to do some housekeeping (as discussed). I will do it through several PRs in order make this process easy to follow.

**Comment by smallfly** [comment]
Hi,

Should we rename the '0.9.0' branch 'master', and add a tag for the version of the add-on compatible with OF 0.8.4 (or even rename 'master' to '0.8.4')?

**Comment by timscaffidi** [comment]
Once 0.9.0 is officially released, I will tag the current master as 0.8.4, then merge 0.9.0 into master, and delete the 0.9.0 branch.

**Comment by smallfly** [comment]
Great! And I'm sure you saw that 0.9.0 has been released.

**Comment by timscaffidi** [comment]
oh yeah I just wasn't sure it was official yet because when I wrote that the download page still had 0.8.4

**Comment by timscaffidi** [comment]
Ok, merged 0.9.0 into master!

**Comment by smallfly** [comment]
Thanks!
I'm planning to do some work on the addon to take advantage of some of OF 0.9.0's new features (i.e. threading)
