### ISSUE TITLE
How to setup for demuxing audio and srt file

### ISSUE THREAD

**Issue by CyrusSUEN** [timscaffidi/ofxVideoRecorder#32]
I have an image sequence to record with an audio mp3 file as the sound source.
So far I can record the image sequence with the mp3 playing in the background of the app and by using [WavTap](https://github.com/pje/WavTap) to hijack the audio stream on Mac OS X 10.10. 

But this solution isn't elegant that I need to install WavTap to capture the audio given I do have a standalone mp3 file already.

```c++
// setting up ofxVideoRecorder
void ofApp::setupVideoRecording() {
    fileName = imageFolder;
    fileExt = ".mov"; 
    
    // override the default codecs if you like
    // run 'ffmpeg -codecs' to find out what your implementation supports (or -formats on some older versions)
    vidRecorder.setVideoCodec("mpeg4");
    vidRecorder.setVideoBitrate("4000k");
    vidRecorder.setAudioCodec("mp3");
    vidRecorder.setAudioBitrate("192k");
    
    // set wavTap as the sound input source
    for (auto i : soundStream.getDeviceList()) {
        if (i.name == "WavTap: WavTap") {
            soundStream.setDeviceID(i.deviceID);
            break;
        }
    }
    
    sampleRate = 44100;
    channels = 2;
    soundStream.setup(this, 0, channels, sampleRate, 256, 4);
    
    vidRecorder.setup(fileName+"-"+ofGetTimestampString()+fileExt, 1920, 1080, appFPS, sampleRate, channels);
}

// recording the audio
void ofApp::audioIn(float *input, int bufferSize, int nChannels){
    if(bRecording)
        vidRecorder.addAudioSamples(input, bufferSize, nChannels);
}
```

There are some container formats supporting demuxing. 
1. How can I put the mp3 file directly in it so that I can get rid of the WavTap part in my app? 
2. If that's possible, how can I also put a srt file within?

Thank you!
And thanks again for making this add-on!:thumbsup:

**Comment by timscaffidi** [comment]
Just to clarify: you have an existing image sequence that you want to mux with an existing audio file?

**Comment by CyrusSUEN** [comment]
> you have an existing image sequence that you want to mux with an existing audio file?

Yes. Is it possible?

**Comment by timscaffidi** [comment]
I am curious why you would choose to write your own program to do this? You could use several existing programs to mux a pre-existing image sequence with a pre-existing soundtrack.

You should be able to accomplish this with just ffmpeg by itself.

**Comment by CyrusSUEN** [comment]
> why you would choose to write your own program to do this?

I'm required to do so for an art installation.
Do you mean I can only deal with ffmpeg directly to accomplish this?

**Comment by timscaffidi** [comment]
Yes, I am saying that ffmpeg can mux video and audio on its own. you shouldn't need to write a custom program to do this. This should get you started: https://en.wikibooks.org/wiki/FFMPEG_An_Intermediate_Guide/image_sequence#Making_a_video_from_an_Image_Sequence

**Comment by timscaffidi** [comment]
I'm going to close this issue as it doesn't apply to this addon specifically. There is a more general issue for openFrameworks in that there is no good way to get access to a "master" channel of audio being generated by the app. You can access audio data that is manually generated using ofSoundStream, AFAIK there is no easy way to get access to the audio samples that are generated from ofSoundPlayer objects, which would be what you are asking for. See #14 and openframeworks/openFrameworks#3741

**Comment by CyrusSUEN** [comment]
> close this issue as it doesn't apply to this addon specifically

OK. And thank you so much for your help!

**Comment by benjgorman** [comment]
@CyrusSUEN Sorry I know this is closed but https://github.com/YCAMInterlab/ofxTimeline may be able to help you. I have used this addon and timeline to produce composited videos automatically. You can take any of the timeline tracks and merge them with frames and then save it all to a video.

**Comment by CyrusSUEN** [comment]
Thanks @benjgorman! I will give it a try.

**Comment by timscaffidi** [comment]
Muxing an image sequence with an mp3 in ffmpeg can be done with a one liner that should be something like this:
```
ffmpeg -f image2 -i "path/to/input_%05d.jpg" -i path/to/audio.mp3 -r <frames per second> -vcodec <video codec name> -acodec copy output_file.mp4
```
This will take an image sequence with a naming scheme of ```path/to/input_#####.jpg``` and produce an mp4 file. This should be a lot quicker and more robust than writing a custom solution.

That being said, if you need some custom processing, then writing your own program is probably the way to go.

**Comment by CyrusSUEN** [comment]
Thanks @timscaffidi ! But I need to do it programmatically because I need some custom processing.
