### ISSUE TITLE
Support directories with spaces

### ISSUE THREAD

**Issue by adielfernandez** [timscaffidi/ofxVideoRecorder#36]
Hey Tim, 

Thanks for putting together this addon. It's just what I need. I'm getting an error I can't find my way around. I've disabled all audio, which got rid of some of the errors except the Bad File Descriptor error. This is the output I get:

```
[warning] ofQTKitGrabber: setDesiredFrameRate(): cannot set framerate for QTKitGrabber
[verbose] ofQTKitGrabber: attached video device: FaceTime HD Camera (Built-in)
[verbose] ofQTKitGrabber: starting video session
bash: VC/ofx_v0.9.1/examples/video/ofxVideoRecorderExample/bin/data/ofxvrpipe0: No such file or directory
[verbose] Recording.

[ error ] ofxVideoDataWriterThread: 12:12:32:542 - write to PIPE failed with error -> 9 - Bad file descriptor.
[warning] The video recorder failed to write some frames!: 
bash: VC/ofx_v0.9.1/examples/video/ofxVideoRecorderExample/bin/data/ofxvrpipe0: No such file or directory
bash: VC/ofx_v0.9.1/examples/video/ofxVideoRecorderExample/bin/data/testMovie2016-03-14-12-12-32-527.mov: No such file or directory
ffmpeg version 3.0 Copyright (c) 2000-2016 the FFmpeg developers
  built with Apple LLVM version 7.0.2 (clang-700.1.81)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.0 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --enable-vda
  libavutil      55. 17.103 / 55. 17.103
  libavcodec     57. 24.102 / 57. 24.102
  libavformat    57. 25.100 / 57. 25.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 31.100 /  6. 31.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[warning] The video recorder failed to write some frames!: 
[warning] The video recorder failed to write some frames!: 
[ error ] ofxVideoDataWriterThread: 12:12:32:628 - write to PIPE failed with error -> 9 - Bad file descriptor.
[warning] The video recorder failed to write some frames!: 
[warning] The video recorder failed to write [s erroor me]  ofxfVirdaemoeDsa!ta:W r
iterThread: 12:12:32:695 - write to PIPE failed with error -> 9 - Bad file descriptor.
[warning] The video recorder failed to wr[i errort e]  osfoxmVei deforDaamteasW!ri:t er
Thread: 12:12:32:729 - write to PIPE failed with error -> 9 - Bad file descriptor.
[warning] The video recorder failed to write some frames!: 
[warning] The video recorder failed to wr[ite  esrormoer  fr] aofxmVeisd!eo:D at
aWriterThread: 12:12:32:794 - write to PIPE failed with error -> 9 - Bad file descriptor.
[warning] The video recorder failed to write some frames!: 
```

The disordered text is pasted as is. I'm guessing both the main and secondary threads are printing to console at once.

Secondary question: I need to simultaneously record many separate videos at once. Do you foresee any problems with having 10-14 simultaneous instances of the ofxVideoRecorder running at once?

Thanks!

**Comment by timscaffidi** [comment]
Hi,
The bad file descriptor seems like exactly that, given the line: 'bash: VC/ofx_v0.9.1/examples/video/ofxVideoRecorderExample/bin/data/ofxvrpipe0: No such file or directory'.

Ensure that the bin/data folder exists and is writable. The addon will not automatically create a data folder inside of bin, so this may be your problem.

As far as multiple instances, there is nothing technically stopping you from recording that many videos at once. It will be however, highly dependent on the specs of the machine you are running on, and what the bitrate is for each stream. As long as you choose a codec that your CPU can handle for that many streams, and you can keep the total bitrate of all streams below the maximum throughput of your storage device, then it should work.

You will have to do some tests with various resolutions/framerates/codecs/quality settings to get this right. It really depends on your machine how much it can handle.

**Comment by adielfernandez** [comment]
Hey Tim,

My data folder was there. Weirdly enough, the "no such file..." error came from there being a space in a folder name about 3 levels above even the OF root folder. I wouldn't have expected something so seemingly far removed from the project folder to be an issue. To anyone else with this issue: make sure there are no spaces in your folder names AND be aware that you may have to re-create the project with the project generator to make sure ofxVideoRecorder has the proper (i.e. no spaces) file structure.

Also, I tested with 10 different videos (640 x 512) all recording simultaneously and it works great. Smooth as butter :) Great addon!

**Comment by timscaffidi** [comment]
@adielfernandez I'm glad you were able to come to a work around on this issue, I'm reopening this to keep track of this bug though. Should be simple enough to fix. Thanks for getting to the bottom of this!

**Comment by timscaffidi** [comment]
I've started looking into this. Apparently OF has problems even compiling when there are spaces in a containing directory. However I was able to replicate this issue by compiling and then renaming the containing folder to have a space, then running the executable.

I've tried a few things to fix this issue to no avail so far but I will continue to poke at it.

**Comment by microcosm** [comment]
I had the same problem on OSX. I was using Google Drive, which by default gives you a working folder with a space in it. I followed [these instructions](https://productforums.google.com/forum/#!topic/drive/Ms8STaowiYw) to change it. Everything working now.

Also, I [used homebrew to install ffmpeg](https://github.com/fluent-ffmpeg/node-fluent-ffmpeg/wiki/Installing-ffmpeg-on-Mac-OS-X) - might be a nice pointer in your readme for OSX users.
