### ISSUE TITLE
What the problem is ?

### ISSUE THREAD

**Issue by MenLonII** [timscaffidi/ofxVideoRecorder#41]
[warning] ofQTKitGrabber: setDesiredFrameRate(): cannot set framerate for QTKitGrabber
[verbose] ofQTKitGrabber: attached video device: FaceTime HD Camera
[verbose] ofQTKitGrabber: starting video session
mkfifo: /Users/xxxxxx/Desktop/OF/Mac/of_v0.9.1_osx_release: File exists
mkfifo: 2/apps/myApps/1_recorder/bin/data/ofxvrpipe0: No such file or directory
mkfifo: /Users/xxxxxx/Desktop/OF/Mac/of_v0.9.1_osx_release: File exists
mkfifo: 2/apps/myApps/1_recorder/bin/data/ofxarpipe0: No such file or directory
[verbose] Recording.

[ error ] ofxAudioDataWriterThread: 14:31:17:801 - write to PIPE failed with error -> 9 - Bad file descriptor.
[ error ] ofxAudioDataWriterThread: 14:31:17:807 - write to PIPE failed with error -> 9 - Bad file descriptor.
[ error ] ofxAudioDataWriterThread: 14:31:17:813 - write to PIPE failed with error -> 9 - Bad file descriptor.
bash: /Users/xxxxxx/Desktop/OF/Mac/of_v0.9.1_osx_release: Permission denied

**Comment by timscaffidi** [comment]
It looks like you have a space in your containing directory 'of_v0.9.1_osx_release 2'

See issue #36
