### ISSUE TITLE
Problems saving  in a specific folder

### ISSUE THREAD

**Issue by aldo-canedo** [timscaffidi/ofxVideoRecorder#58]
Hello, 

I'm having problems to save my file in a specific folder, any suggestion?

Here's the code:

    if(key=='r'){
        bRecording = !bRecording;
        if(bRecording && !vidRecorder.isInitialized()) {
      
           vidRecorder.setupCustomOutput(vidGrabber.getWidth(), vidGrabber.getWidth(), 30,"/Users/usuario/Google Drive/test.mov");
           
            vidRecorder.start();
        }

Hope you can help me.

Thanks.

**Comment by timscaffidi** [comment]
The only thing I can think of at the moment is that there is a space in the path from "Google Drive". However, I thought this issue had been fixed.
Can you help test this out?
1. Does it work if you use a path without a space in it?
2. Does it work if you use a different path that *does* have a space in it?

**Comment by aldo-canedo** [comment]
Thanks @timscaffidi, it works when I use a different path but the video its corrupted, the same video captured in the example version works perfectly.

Here's my new path:

       vidRecorder.setupCustomOutput(vidGrabber.getWidth(), vidGrabber.getWidth(), 30,"/Users/aldo/Documents/test.mov");

and the console prints this message:

T[he vreecoded video file isr bnoow scomplete.e
] ofxVideoDataWriterThread: closing pipe: /Users/aldo/Documents/of_v0.9.2_osx_release/apps/myApps/ofxVideoRecorderExample/bin/data/ofxvrpipe0
[rawvideo @ 0x102800000] Invalid buffer size, packet size 960000 < expected frame_size 1920000
Error while decoding stream #0:0: Invalid argument

**Comment by timscaffidi** [comment]
@aldo-canedo, using `setupCustomOutput()` is a more advanced way to use the recorder, usually reserved for things like network streaming. This method assumes you pass all of the options necessary to ffmpeg for output, not just the output path.  I would recommend using the simpler `setup()` method in combination with `setVideoCodec()` and its ilk.

**Comment by aldo-canedo** [comment]
Works perfect!! thanks so much for your help.
