### ISSUE TITLE
Support for OF 0.10.0

### ISSUE THREAD

**Issue by teganscott** [timscaffidi/ofxVideoRecorder#61]
Hello,

Is there support planned for OpenFrameworks 0.10.0? Getting the error of "Poco/Condition.h' file not found" in the example but do not get in OF 9.8

Thank you,

Tegan

**Comment by teganscott** [comment]
If anyone else has this issue the addon ofxPoco needs to be included in the makefile

**Comment by moebiussurfing** [comment]
hey @teganscott , I tried this solution but i am getting this:

not found <unistd.h
https://github.com/timscaffidi/ofxVideoRecorder/issues/62

I what something to record my 3D render with good performance... Any alternative advice is welcome

**Comment by teganscott** [comment]
@moebiussurfing I tried it again with the stable release of OF 10.0 and don't seem to have that problem. Do you have ffmeg installed as described in the Readme?

In the end I decided to save each individual frame as an image because that fit better with my project's needs. If you are still having issues, you could try that and then composite the images together into a video.
